#!/usr/bin/env node
var mv = require('fs').renameSync
var basenames = require('./files.json')
var path = require('path')

basenames.forEach(function(basename) {
  process.stdout.write('Moving ' + basename.build + '\n')
  try {
    mv(
      path.join('build', ( basename.build + '.docx' )),
      path.join('build', ( basename.github + '.docx' ))) }
  catch (error) {
    /* ignore */ }
  try {
    mv(
      path.join('build', ( basename.build + '.pdf' )),
      path.join('build', ( basename.github + '.pdf' ))) }
  catch (error) {
    /* ignore */ } })
