#!/usr/bin/env node
var plaintemplate = require('plaintemplate')
var fs = require('fs')

var INDENT = /^ {4}/
var EMPTY_LINE = /^(\s*)$/

var buffers = [ ]
process.stdin
  .on('data', function(buffer) {
    buffers.push(buffer) })
  .on('end', function() {
    process.stdout.write(
      plaintemplate(
        Buffer.concat(buffers).toString(),
        // empty context
        { },
        function handler(token) {
          var directive = token.tag.trim()
          if (directive.startsWith('include')) {
            return read(fileName(directive.split(' ')[1]))
              // split lines
              .split('\n')
              .map(function(line, index) {
                return (
                  EMPTY_LINE.test(line) ?
                    // If the line is empty, leave it empty.
                    line :
                    ( index === 0 ?
                      // On the first line, replace all indentation with spaces
                      // reflecting the indentation of the template tag in the
                      // template.
                      line.replace(/^ +/, '') :
                      // On subsequent lines with indentation, add spaces to
                      // existing indentation.
                      line.replace(INDENT, ' '.repeat(token.position.column - 1) )) ) })
              .join('\n') } },
        { open: '((', close: '))', start: '{', end: '}' })) })
  .resume()

function read(file) {
  return fs.readFileSync(file).toString() }

function fileName(basename) {
  return ( './includes/' + basename + '.cform' ) }
